name: Terraform-Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: 
      name: ${{ inputs.environment}}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory
    - name: Terraform Init
      working-directory: ./Terraform/QuickStartDeployments/EKSCluster
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: ./Terraform/QuickStartDeployments/EKSCluster
      run: terraform plan -var-file="dev-variables.tfvars"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      working-directory: ./Terraform/QuickStartDeployments/EKSCluster
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file="dev-variables.tfvars"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}