name: 'Terraform CI'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  dev-deployment:
    uses: LefeWareSolutions/GoogleCloudPlatformIaCTemplates/.github/workflows/deploy-terraform.yml@main
    with:
      environment: dev
    secrets:
      GCP_SA_KEY : ${{ secrets.GCP_SA_KEY }}

  prd-deployment:
    uses: LefeWareSolutions/GoogleCloudPlatformIaCTemplates/.github/workflows/deploy-terraform.yml@main
    with:
      environment: prd
    secrets:
      GCP_SA_KEY : ${{ secrets.GCP_SA_KEY }}